frontend/controllers/BillnController.php
<?php

namespace frontend\controllers;

use kartik\mpdf\Pdf;
use yii\helpers\Url;


class BillnController extends \yii\web\Controller
{
    public function actionIndex()
    {
        $page = 1;
        $data = [
            'income_type' => '2',
            'logo' => 'ischool.png',
            'Receipt' => 'ใบกำกับภาษี / ใบเสร็จรับเงิน',
            'Code_Bill' => 'BILL123004',
            'Date_Bill' => date('d/m/Y'),
            'Seller_Bill' => 'บัญชี  ซื่อสัตย์',
            'Date_duly' => date('d/m/Y'),
            'name' => 'บริษัท เนกเจน แอนด์ เนทออพ จำกัด',
            'address' => '1558/41 ถ.บางนา-ตราด',
            'sub_district' => 'แขวงบางนา',
            'district' => 'เขตบางนา',
            'province' => 'กรุงเทพฯ',
            'postal_code' => '10260',
            'branch' => 'สำนักงานใหญ่',
            'tax_id' => '0105559127204',
            'telephone' => '02-101-4822',
            'Customer_name' => 'สมาคมผู้ปกครองและครูโรงเรียนถาวรานุกุล',
            'Customer_address' => '99/9 ม.2 ต.หนองปรือ อ.บางพลี จ.สมุทรปราการ 10260',
            'Customer_tax_id' => '099400042493',
            'Note' => 'โปรดจ่ายเช็คขีดคร่อมในนาม  บริษัท เนกเจน แอนด์ เนทออพ จำกัด หรือโอนเข้าบัญชี ธนาคารกสิกรไทย สาขาเซ็นทรัลบางนา
                     ชื่อบัญชี : บริษัท เนกเจน แอนด์ เนทออพ จำกัด
                     เลขที่บัญชี : 016-1-97701-2',
        ];
        $footer = $this->renderPartial('_billnfooter', [
            'data' => $data,
        ]);
        $content = $this->renderPartial('setpage', [
            'page' => $page,
            'data' => $data,

        ]);
        $mpdf = new \mPDF('th', 'A4', '0', '', $left = '10', $right = '5', $top = '5', '30');
        $stylesheet = file_get_contents(\Yii::getAlias('@frontend/web/mpdf/bill.css'));
        $mpdf->SetHTMLFooter($footer);
        if ($data['income_type'] == 0) {
            $mpdf->SetTitle('ใบเสนอราคา');
        } elseif ($data['income_type'] == 1) {
            $mpdf->SetTitle('ใบวางบิล');
        } elseif ($data['income_type'] == 2) {
            $mpdf->SetTitle('ใบเสร็จรับเงิน');
        }
        $mpdf->WriteHTML($stylesheet, 1); //เพิ่ม css
        $mpdf->WriteHTML($content, 2);
        $mpdf->Output();
    }

    public function actionFont()
    {
//        $content=$this->renderPartial('font');
//       $mpdf =new mPDF('th','A4','');
//        $mpdf->SetFont('THSarabunNew');
//        $mpdf->WriteHTML($content);
//        $mpdf->Output();
        return $this->render('font');
    }
}

frontend/controllers/CertificateController.php
<?php

namespace frontend\controllers;

class CertificateController extends \yii\web\Controller
{


public function actionCerCate()
{
    //ใบสำคัญรับ
    $content =$this->renderPartial('index');
    $header=$this->renderPartial('headercer-cate');
    $footer=$this->renderPartial('foottercer-cate');
    $mpdf = new \mPDF('th', 'A4','0','thsaraban', $left = '15', $right = '5', $top = '60', '20');
    $stylesheet = file_get_contents(\Yii::getAlias('@frontend/web/css/certificate.css'));
    $mpdf->SetHTMLHeader($header);
    $mpdf->WriteHTML($stylesheet, 1); //เพิ่ม css
    $mpdf->WriteHTML($content,2);
    $mpdf->SetHTMLFooter($footer);
    $mpdf->Output();
}

public function actionMake()
{

    //รายงาน กระดาษทำการ
    $header=$this->renderPartial('headermake');
    $content =$this->renderPartial('make');
    $mpdf = new \mPDF('th', 'A4','0','', $left = '20', $right = '10', $top = '40', '20');
    $stylesheet = file_get_contents(\Yii::getAlias('@frontend/web/css/makes.css'));
    $mpdf->SetTitle('รายงาน');
    $mpdf->SetHTMLHeader($header);
    $mpdf->WriteHTML($stylesheet, 1); //เพิ่ม css
    $mpdf->WriteHTML($content,2);
    $mpdf->Output();
}
public function actionBudget()
{
    //รายงาน งบทดลอง
    $header=$this->renderPartial('headerbudget');
    $content =$this->renderPartial('budget');
    $mpdf = new \mPDF('th', 'A4','0','', $left = '20', $right = '10', $top = '45', '10');
    $stylesheet = file_get_contents(\Yii::getAlias('@frontend/web/css/makes.css'));
    $mpdf->SetTitle('รายงาน');
    $mpdf->SetHTMLHeader($header);
    $mpdf->WriteHTML($stylesheet, 1); //เพิ่ม css
    $mpdf->WriteHTML($content,2);
    $mpdf->Output();
}
public function actionBalance()
{
    //รายงานงบดุล
    $content =$this->renderPartial('balance');
    $mpdf = new \mPDF('th', 'A4','0','', $left = '15', $right = '10', $top = '20', '10');
    $stylesheet = file_get_contents(\Yii::getAlias('@frontend/web/css/makes.css'));
    $mpdf->SetTitle('รายงานงบดุล');
    $mpdf->WriteHTML($stylesheet, 1); //เพิ่ม css
    $mpdf->WriteHTML($content,2);
    $mpdf->Output();
}
public function actionStatements()
{
    //งบกำไรขาดทุน
    $content =$this->renderPartial('statements');
    $mpdf = new \mPDF('th', 'A4','0','', $left = '15', $right = '10', $top = '20', '10');
    $stylesheet = file_get_contents(\Yii::getAlias('@frontend/web/css/makes.css'));
    $mpdf->SetTitle('รายงานงบกำไรขาดทุน');
    $mpdf->WriteHTML($stylesheet, 1); //เพิ่ม css
    $mpdf->WriteHTML($content,2);
    $mpdf->Output();
}
    public function actionAccount()
    {
        //รายงานบัญชี
        $content =$this->renderPartial('account');
        $mpdf = new \mPDF('th', 'A4','0','', $left = '5', $right = '10', $top = '15', '10');
        $stylesheet = file_get_contents(\Yii::getAlias('@frontend/web/css/makes.css'));
        $mpdf->SetTitle('รายงานบัญชี');
        $mpdf->WriteHTML($stylesheet, 1); //เพิ่ม css
        $mpdf->WriteHTML($content,2);
        $mpdf->Output();
    }

    public function actionReportCard()
    {
        $content =$this->renderPartial('cardwork');
        $mpdf = new \mPDF('th', 'A4','0','', $left = '15', $right = '10', $top = '15', '10');
        $stylesheet = file_get_contents(\Yii::getAlias('@frontend/web/css/cardwork.css'));
        $mpdf->SetTitle('ใบตรวจรับงาน');
        $mpdf->WriteHTML($stylesheet, 1); //เพิ่ม css
        $mpdf->WriteHTML($content,2);
        $mpdf->Output();

    }

}

frontend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'รายงาน',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-default navbar-fixed-top',
        ],
    ]);
    $menuItems = [
        ['label'=>'ใบสำคัญ+จ่าย+รับ+ทั่วไป','url'=>['/certificate/cer-cate']],
        ['label'=>'รายงานบัญชี','url'=>['/certificate/account']],
        ['label'=>'งบกำไรขาดทุน','url'=>['/certificate/statements']],
        ['label'=>'งบดุล','url'=>['/certificate/balance']],

        ['label' => 'print',['htmlOptions'=> array('onclick' => 'addtolist()')]],
        ['label' => 'ใบวางบิล', 'url' => ['/billn/index']],
        ['label' => 'กระดาษทำการ', 'url' => ['/certificate/make']],
        [ 'label'=>'งบทดลอง','url'=>['/certificate/budget']],
    ];
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Signup', 'url' => ['/site/signup']];
        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
    } else {
        $menuItems[] = '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                'Logout (' . Yii::$app->user->identity->username . ')',
                ['class' => 'btn btn-link logout']
            )
            . Html::endForm()
            . '</li>';
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>

        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<!--<footer class="footer">-->
<!--    <div class="container">-->
<!--        <p class="pull-left">&copy; My Company --><?//= date('Y') ?><!--</p>-->
<!---->
<!--        <p class="pull-right">--><?//= Yii::powered() ?><!--</p>-->
<!--    </div>-->
<!--</footer>-->

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

frontend/views/layouts/pdf.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;

//\frontend\assets\AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">


    <div class="container">

        <?= $content ?>

</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>